<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
        <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)</OpenApiDocumentsDirectory>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DocumentationFile>bin\Debug\net10.0\Books.WebApi.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\net10.0\Books.WebApi.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Books.Application\Books.Application.csproj" />
      <ProjectReference Include="..\Books.Infrastructure\Books.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    </ItemGroup>

    <PropertyGroup>
        <ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
    </PropertyGroup>

</Project>
